# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15iFPmtDQQJcG9aKlHSH8PayZAhRetal2
"""

import numpy as np
# creating array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
zeros_arr = np.zeros((3, 3), dtype=int)
print(zeros_arr)
ones_arr = np.ones((2, 2), dtype=int)
print(ones_arr)
arange_arr = np.arange(10)
print(arange_arr)
#array manipulation
reshape_arr = arr.reshape(5,1)
print(reshape_arr)
#sliced
sliced_arr = arr[2:4]
print(sliced_arr)

import numpy as np
#linear algebra with numpy
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a,b)
print(c)
d = np.linalg.eig(c)
print(d)
#1
a = np.array([[5,6,7],
 [8,9,6]])
b = np.sum(a)
print(b)
#2
a = np.array([[1,2,7],[3,4,5]])
c = np.sum(a,axis=0)
d = np.sum(a,axis=1)
print(c)
print(d)
#3
a=np.array([1,2,3,4,5])
b=np.mean(a)
print(b)
c=np.median(a)
print(c)
d=np.var(a)
print(d)
e=np.std(a)
print(e)

import pandas as pd
a = ["fathima","thrishuna","mounika","rushitha","durga"]
r = pd.Series(a, index=[1,2,3,4,5])
print(r)

import pandas as pd
df = pd.read_csv("/content/archive (4).zip")
print(df)

df = pd.read_csv("/content/TXT.txt",sep=" ")
print(df)

df = pd.read_excel("/content/excel.xlsx" ,sheet_name=0)
print(df)

df = pd.read_excel("/content/mean.xlsx")
print(df)
mv = df['sem'].mean
df = df.fillna(mv)
print(mv)

df = pd.read_excel("/content/Copy of Book1(2).xlsx")
print(df)
df = df.drop_duplicates()
print(df)

df = pd.read_excel("/content/mean.xlsx")
df.head(5)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/archive (4).zip")
a=df.head(10)
b=df.tail(10)
c=pd.concat([a,b],axis=0)
print(c)
c.to_csv("manipulate_testing.csv")
print(c.groupby(['Postcode'])['Latitude'].count())

#cricket
import numpy as np
import matplotlib.pyplot as plt
runs = np.array([100,50,91,78,89,25,34,19,9,10])
w = np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(runs,w,color='orange')
plt.title('IndvsAus_score')
plt.show()



#trignomatical
import numpy as np
import matplotlib.pyplot as plt
tigar = np.linspace(-2*np.pi, 2*np.pi, 50)
print(tigar)
plt.scatter(tigar, np.sin(tigar), color='black')
plt.title("sin(x)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
overs = np.arange(5, 50, 5)
overs_a = np.arange(5, 30, 5)
runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])
plt.plot(overs,runs_i,color='blue',label='India')
plt.subplot(2,1,2)
plt.plot(overs_a,runs_a,color='yellow',label='Aus')
plt.subplot(2,1,1)
plt.legend(loc='best')
plt.show()

import matplotlib.pyplot as plt

a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth='3',label='CompanyA',marker='.',ms='10',mec='k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label='CompanyB',marker='H')

a=np.array([25,60,5,10])
labe=["AIML","Python","Pandas","Numpy"]
colours=['green','red','black','blue']
explo=[0.1,0,0.2,0]
plt.pie(a,colors=colours,labels=labe,explode=explo,startangle=10)
plt.show()

import numpy as np
import pandas as pd
df=pd.read_csv("/content/daily_temperature.csv - Sheet1.csv")
print(df)
average_temperature=df["temperature (Celsius)"].mean()
highest_temperature=df['temperature (Celsius)'].max()
lowest_temperature=df['temperature (Celsius)'].min()
threshold=30
days_above_threshold=df[df['temperature (Celsius)']>threshold].shape[0]
print("Average temperature for the month:",average_temperature)
print("Highest_temperature recorded:",highest_temperature)
print("Lowest_temperature recorded:",lowest_temperature)
print("number of days where temperature exceeded",threshold,"degree Celsius:",days_above_threshold)

pip install seaborn

#Day 3
import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip", data=tips)
plt.title("Scatter plot of total bill vs. tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris)
sns.scatterplot(x="sepal_length", y="sepal_width", data=iris)
plt.title("iris")
plt.xlabel("sepal_length")
plt.ylabel("sepal_width")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
flights=sns.load_dataset("flights")
print(flights)
sns.scatterplot(x="year", y="month", data=flights)
plt.title("flights")
plt.xlabel("year")
plt.ylabel("month")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill", data=tips)
plt.title("Distribution of Total Bill by Day")
plt.xlabel("Day of the week")
plt.ylabel("Total Bill ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris=sns.load_dataset("iris")
print(iris.head(20))
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap of Iris Dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
planets=sns.load_dataset("planets")
print(planets)
correlation_matrix=planets.corr()
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap of planets Dataset")
plt.show()